2024-11-19 15:46:58,029 [INFO] Starting Discord bot and web dashboard...
2024-11-19 15:46:58,031 [INFO] logging in using static token
2024-11-19 15:46:59,956 [CRITICAL] Critical error starting services: Improper token has been passed.
2024-11-19 15:47:20,368 [INFO] logging in using static token
2024-11-19 15:47:21,456 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:21,471 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:22,204 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:22,206 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:22,778 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:22,779 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:23,469 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:23,471 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:24,338 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:24,340 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:24,997 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:24,999 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:25,657 [ERROR] Error generating activity graph: No columns to parse from file
2024-11-19 15:47:25,659 [ERROR] Full traceback: Traceback (most recent call last):
  File "/home/kali/Desktop/bot/main2.py", line 256, in get_activity_graph
    df = pd.read_csv(log_file)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/bot/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

2024-11-19 15:47:46,539 [INFO] logging in using static token
2024-11-19 15:47:47,406 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:48,209 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:48,313 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:48,951 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:49,672 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:50,504 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:51,415 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:52,170 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:53,166 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:53,785 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:54,476 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:55,179 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:55,869 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:56,596 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:57,433 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:58,308 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:58,984 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:47:59,762 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:00,628 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:01,417 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:02,264 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:03,194 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:04,118 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:04,893 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:05,862 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:07,075 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:08,100 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:09,180 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:10,493 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:11,598 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:12,460 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:13,487 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:15,035 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:16,315 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:18,113 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:20,715 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:21,829 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:23,362 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:24,856 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:48:26,738 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:30,933 [INFO] logging in using static token
2024-11-19 15:49:31,980 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:32,664 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:33,479 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:34,321 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:35,265 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:36,321 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:37,249 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:38,180 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:49:39,116 [INFO] Sample timestamp from data: 2024-11-11 00:13:25.925926
2024-11-19 15:52:20,141 [ERROR] Startup error: name 'run_fastapi' is not defined
2024-11-20 14:15:19,669 [INFO] logging in using static token
2024-11-20 14:15:21,822 [INFO] Bot initialized for guild: BeyondAI
2024-11-20 14:15:22,483 [INFO] Slash commands synced with Discord
2024-11-20 14:15:23,607 [INFO] Shard ID None has connected to Gateway (Session ID: 362f9cc1b441ee45dbfefe5a124e883c).
2024-11-20 14:15:25,710 [INFO] Bot is ready! Logged in as BeyondAI
2024-11-20 14:15:35,921 [ERROR] Error generating activity graph: time data "2024-11-11 04:22:11.966276" doesn't match format "%Y-%m-%dT%H:%M:%S.%f", at position 4. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
2024-11-20 14:15:37,135 [ERROR] Error generating activity graph: time data "2024-11-11 04:22:11.966276" doesn't match format "%Y-%m-%dT%H:%M:%S.%f", at position 4. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
